options v4l2loopback exclusive_caps=1 card_label="OBS Virtual Camera"

### These modules must be blacklisted for use with broadcom-wl
blacklist ssb
blacklist bcma
blacklist b43
blacklist brcmsmac
blacklist brcmfmac